Add Login control

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -133,7 +133,11 @@ jobs:
     - name: Login to server
       run: |
         response=$(curl -X POST -H "Accept: Application/json" -H "Content-Type: application/json" ${{ secrets.STAGING_SERVER_URL }}/rest/v2/users/authenticate -d '{"email":"${{ secrets.USER_NAME }}","password":"${{ secrets.PASSWORD }}"}' -c cookie.txt)
-        
+        success=$(echo $response | jq -r '.success')
+        if [ "$success" != "true" ]; then
+          echo "Login failed"
+          exit 1
+        fi
     - name: Check if App Exists
       run: |
         response=$(curl -s -o /dev/null -w "%{http_code}" -H "Accept: Application/json" -H "Content-Type: application/json" "${{ secrets.STAGING_SERVER_URL }}/rest/v2/applications/Conference" -b cookie.txt)
